feat: migrate to typescript & rollup
steverydz/build-url pull request #40
Opened 2020-08-30 13:39 UTC by meabed

- migrate to typescript 
- migrate build to rollup 
- prettier

2020-08-30 16:40 UTC, steverydz requested changes
Thanks for taking the time to do this. I have some comments to address in the code, and the `npm run build` command gives an error (see TravisCI build details).

```bash
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
```

2020-08-30 16:40 UTC, steverydz commented on .gitignore
> +.idea
IDE specific files should be added to your global gitignore, not in the project

2020-08-30 16:40 UTC, steverydz commented on jest.config.js
> +};
Needs a newline at the end of the file

2020-08-30 16:40 UTC, steverydz commented on package.json
> +    "prettier": "npx prettier --write '**/*.{ts,tsx,css,scss}'"
prettier is already a dependency of this project so `npx` shouldn't be needed, although I can't see where this is used?

2020-08-30 16:40 UTC, steverydz commented on package.json
> +    "@rollup/plugin-typescript": "^5.0.2",
please pin the dependency

2020-08-30 16:40 UTC, steverydz commented on package.json
> +    "@types/jasmine": "^3.5.14",
please pin the dependency

2020-08-30 16:40 UTC, steverydz commented on package.json
> +    "@types/jest": "^26.0.10",
please pin the dependency

2020-08-30 16:40 UTC, steverydz commented on package.json
> +    "@typescript-eslint/parser": "^3.10.1",
please pin the dependency

2020-08-30 16:40 UTC, steverydz commented on package.json
> +    "rollup": "^2.26.8",
please pin the dependency

2020-08-30 16:40 UTC, steverydz commented on package.json
> +    "ts-jest": "^26.3.0",
please pin the dependency

2020-08-30 16:40 UTC, steverydz commented on package.json
> +    "tslib": "^2.0.1",
please pin the dependency

2020-08-30 16:40 UTC, steverydz commented on package.json
> +    "typescript": "^4.0.2"
please pin the dependency

2020-08-30 21:27 UTC, meabed commented
Thanks for the comments :) I have fixed them! and it looks good now.

2020-08-31 08:20 UTC, meabed commented
Sounds good :) Thanks for the support!

2020-08-31 08:20 UTC, closed without merging